export const CREATE_NEW_USER = "CREATE_NEW_USER"
export const LOGIN_USER = "LOGIN_USER"
export const INSERT_AVATAR = "INSERT_AVATAR"
export const GET_ONE_MASSAGES = "GET_ONE_MASSAGES"
export const GET_ALL_MASSAGES = "GET_ALL_MASSAGES"
export const GET_ERROR = "GET_ERROR"
export const ALL_USER = "ALL_USER"

export const CREATE_MASSAGES = "CREATE_MASSAGES"